### ISSUE TITLE
Handling multiple electrodes during fine-tuning

### ISSUE THREAD

**Issue by Sreyan88** [czlwang/BrainBERT#2]
Hi there, great work!

You mention in your paper that for BrainBERT pre-training you STFT/Superlet each individual electrode to get time-frequency representations. However, I wanted to know how do you handle multiple electrodes during the fine-tuning stage.

Thank You!

**Comment by czlwang** [comment]
Hi! We fine-tune _per_ each electrode. So at all points, the input is only ever the activity from a single electrode.
