### ISSUE TITLE
Code for fine-tuning 

### ISSUE THREAD

**Issue by dyhan316** [czlwang/BrainBERT#6]
Could you please provide how to do fine-tuning? Thank you!

**Comment by ZhanCary66** [comment]
hi, @dyhan316 ,have you known how to fine-tuning now?

**Comment by dyhan316** [comment]
sorry for the late reply! was busy with a paper. 

anyway, I contacted them and they said that fine-tuning code is not releastefd yet... I made my own using standard PyTorch haha
